#!/bin/bash

# Mentor-Mentee Mapping Workspace Build Script
echo "🎯 Mentor-Mentee Mapping Workspace Setup & Build Guide"
echo "====================================================="
echo ""

echo "📁 Project Structure:"
echo "mentor-mentee-mapping/"
echo "├── 🗂️  backend/           # Node.js Express API"
echo "│   ├── 📄 server.js       # Main server file"
echo "│   ├── 📄 package.json    # Backend dependencies"
echo "│   └── 📁 data/           # JSON data storage"
echo "│       ├── mentors.json   # Mentor profiles"
echo "│       └── mentees.json   # Mentee profiles"
echo "├── 🗂️  frontend/          # React application"
echo "│   ├── 📄 package.json    # Frontend dependencies"
echo "│   ├── 📁 public/         # Static assets"
echo "│   └── 📁 src/            # React source code"
echo "│       ├── 📄 App.js      # Main app component"
echo "│       └── 📁 components/ # React components"
echo "└── 📄 package.json        # Root package.json"
echo ""

echo "🛠️  How to Build This Workspace:"
echo ""

echo "1️⃣  Install All Dependencies:"
echo "   npm run install-all"
echo "   # OR manually:"
echo "   cd backend && npm install"
echo "   cd ../frontend && npm install"
echo ""

echo "2️⃣  Start Backend Server (Port 3001):"
echo "   cd backend"
echo "   npm start"
echo "   # Backend API will be available at http://localhost:3001"
echo ""

echo "3️⃣  Start Frontend Development Server (Port 3000):"
echo "   cd frontend"
echo "   npm start"
echo "   # React app will be available at http://localhost:3000"
echo ""

echo "4️⃣  Or Start Both Concurrently:"
echo "   npm run dev"
echo "   # Starts both backend and frontend simultaneously"
echo ""

echo "🎯 Key Features:"
echo "✅ Smart mentor-mentee matching algorithm"
echo "✅ Interactive 5-question assessment"
echo "✅ Real-time compatibility scoring"
echo "✅ JSON-based data persistence"
echo "✅ Responsive React UI"
echo "✅ RESTful API with Express.js"
echo ""

echo "🔗 API Endpoints:"
echo "📊 GET  /health           - Health check"
echo "📊 GET  /matches          - View all data"
echo "📊 POST /mentor           - Register mentor"
echo "📊 POST /mentee           - Register mentee + get match"
echo ""

echo "💡 Usage Flow:"
echo "1. Visit http://localhost:3000"
echo "2. Choose 'Mentor' or 'Mentee' role"
echo "3. Answer 5 compatibility questions"
echo "4. Get instant matching results"
echo ""

echo "🚀 Backend Status: $(curl -s http://localhost:3001/health 2>/dev/null && echo "✅ Running" || echo "❌ Not Running")"
echo "🎨 Frontend Status: $(curl -s http://localhost:3000 2>/dev/null && echo "✅ Running" || echo "❌ Not Running")"
echo ""

echo "📚 Documentation: See README.md for detailed setup instructions"
echo "🏗️  Tech Stack: React + Node.js + Express + JSON Storage"
